apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: postgres
          namespace: namespace_name
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: postgres
          template:
            metadata:
              labels:
                app: postgres
            spec:
              containers:
              - name: postgres
                image: postgres:latest
                env:
                  - name: POSTGRES_DB
                    value: "synapse"
                  - name: POSTGRES_USER
                    value: "postgres_user"
                  - name: POSTGRES_PASSWORD
                    value: "postgres_password"
                ports:
                  - containerPort: 5432
                volumeMounts:
                  - name: postgres-data
                    mountPath: /var/lib/postgresql/data
              volumes:
                - name: postgres-data
                  persistentVolumeClaim:
                    claimName: postgres-pv-claim
